### ISSUE TITLE
Interactive display using sentinelhub + streamlit + folium

### ISSUE THREAD

**Issue by murraycutforth** [SimonFisher92/Scottish_Snow#17]
I've built on top of @EddieBoyle2019's streamlit app, so that you can select a snow patch and a date, and then the imagery is displayed as an overlay on a terrain map, using a python package called folium to get interactive maps.

Currently looks like this:

![image](https://github.com/SimonFisher92/Scottish_Snow/assets/11088372/03443cbb-f603-4ec2-b94c-cc10b2d02b68)

It's good fun to play around with, although I haven't managed to get the cloud mask option to work (still need to look into the error which it raises). But the overlay looks correct, you can see snow patches sitting below ridge lines and in gullies which is very satisfying!

I'll park this on a new branch for now. It should be easy to get running, just pip install the extra packages in the requirements.txt file and then run `streamlit run main.py`.

**Comment by EddieBoyle2019** [comment]
Hello Murray, this is pretty much exactly what I was going to do in the next iteration of the prototype! Your dev work looks great.

**Comment by murraycutforth** [comment]
I'm going to close this for now, see also: https://github.com/murraycutforth/Scottish_Snow_Visualisation
