### ISSUE TITLE
Normalise calculated area to patch angle (steepness)

### ISSUE THREAD

**Issue by SimonFisher92** [SimonFisher92/Scottish_Snow#2]

**Comment by murraycutforth** [comment]
I touched on this on my other post, how about using the 30m resolution elevation model from the elevation package (https://pypi.org/project/elevation/) to get the surface gradient?

**Comment by SimonFisher92** [comment]
@murraycutforth has generated a solution for elevation with @SimonFisher92 adding functionality for slope direction
