### ISSUE TITLE
Additional features for new download code

### ISSUE THREAD

**Issue by murraycutforth** [SimonFisher92/Scottish_Snow#26]
- All 13 bands should be downloaded
- Data should be saved both as png (for looking at RGB) and as .npz (numpy arrays with all 13 bands)
- Copernicus authentication should be via a config file which git ignores (so we don't accidentally commit credentials)
- Separate data by year
- Set size of bounding box

**Comment by murraycutforth** [comment]
Okay @ipoole, @SimonFisher92, if you guys want to run the download script (renamed to src/download/main.py) I think it's working but I can't test it any longer as I've run out of requests for the month. The requirements.txt should be up to date and the only other thing you need to do is add a small local config file called "config.json" with your credentials inside:

    {
      "client_id": "..",
      "client_secret": "..."
    }

**Comment by murraycutforth** [comment]
If this works for you guys I'll start a PR to merge it into master.

**Comment by murraycutforth** [comment]
I've added code to get all 13 bands, the CLS mask, SNW and CLD probabilities, and pixel heights from a digital elevation map which conveniently is also accessible through the copernicus data hub!

The code stores the arrays as .npy files, and also outputs pngs for convenient browsing. Here is example data (beinn a bhuird, 2nd July 2018):

RGB image:
![S2A_MSIL1C_20180702T113321_N0206_R080_T30VVJ_20180702T132802 SAFE](https://github.com/SimonFisher92/Scottish_Snow/assets/11088372/1e961c6a-ff5a-439b-abeb-a342939bce51)

digital elevation map:
![Beinn_a_Bhuird_dem](https://github.com/SimonFisher92/Scottish_Snow/assets/11088372/42b28753-ab31-477f-ab6d-e0880faf89f0)

I've uploaded all data for beinn a bhuird from 2018-2022 here: https://www.dropbox.com/scl/fo/1a5axf6an3yh8g2npbml8/h?rlkey=7lokur69l91t3brkd4pt8jaqg&dl=0 

However, now that I'm looking more closely it appears that the L2A data (the masks) doesn't line up with the L1C data (the raw band values), and I don't know why. Seems like this needs a bit more investigation..

**Comment by murraycutforth** [comment]
I've looked again, and I must have been mistaken as it does look like all the masks do correspond to the band data, but very occasionally there is no L2A mask for the L1C image- maybe their L2A processing fails occasionally?

Anyway all the data I've downloaded (all patches, 2018-2022) I've made available on dropbox here: https://www.dropbox.com/scl/fo/m31xb8eaz1su3ts77nfi5/h?rlkey=dttzxerq0bqoq4vk7isf776z4&dl=0

**Comment by ipoole** [comment]
Thanks Murray, I'm downloading the data from Dropbox now, one patch at a time...
I'll use this data to make a start on a sklearn pipeline for pixel level classification.
Let me know when you have a PR for me to look at, to get your code onto master.  Ian.

**Comment by ipoole** [comment]
Ok I just spoke to Simon.  I was looking at only the L2a data.  I see that in the L1C data the .npy files each contain 13 channels.   So all good, sorry for being dumb.

**Comment by SimonFisher92** [comment]
The DEM data is excellent, but i think slope direction is just as important as altitude, im going to add a function to the branch to incoporate directional data. All the snowpatches sit in norh east facing corries

**Comment by SimonFisher92** [comment]
![image](https://github.com/SimonFisher92/Scottish_Snow/assets/98879661/fc620c89-7ae4-416a-95fc-a179aa562262)


Pixel intensity of this is based on Murrays altitude dems, but colour now is based on slope direction. I would put money on long lasting patches being in bright purple/blue/red

**Comment by SimonFisher92** [comment]
Small push to the branch (10-new_copernicus_api_trial) to add this functionality

**Comment by ipoole** [comment]
Very nice Simon!   This will be very useful in a per-pixel classifier.  Of course in a CNN setting it would (should) discover the gradient for its self.   Just thinking how to encode the slope; could be gradient in each of x and y direction or angle and magnitude.   I.e. Cartesian or circular coordinates.   Btw, I take it all our patches are compass oriented?  Y axis N-S?

**Comment by SimonFisher92** [comment]
Yes, agreed re CNN- was thinking of this pure for pixel level. Good question about encoding. You could have 4 features, one for each NESW, presumably each pixel would be a combination of 2/4 of these values? Altitude could be another feature. If that were the approach, then i would definitely want to be sure of the model picking up relationships between these features. There might be another, more refined way to do it.

**Comment by ipoole** [comment]
I don't see the need for 4 features, 2 should be sufficient.  In the Cartesian scheme you have gradient components in N-S and E-W, both of which can be +ve or -ve.

**Comment by murraycutforth** [comment]
> ![image](https://private-user-images.githubusercontent.com/98879661/289129526-fc620c89-7ae4-416a-95fc-a179aa562262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMzQxOTksIm5iZiI6MTcwMzAzMzg5OSwicGF0aCI6Ii85ODg3OTY2MS8yODkxMjk1MjYtZmM2MjBjODktN2FlNC00MTZhLTk1ZmMtYTE3OWFhNTYyMjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAwNTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMTYyZGNjYTcwMzFiMGI2ZGZjYTg1ZTZmNmZmZWFiNWMwZDdiNWIyYzNkNjU4NmJhNDU2MjU4ZjJjNjExZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QOsYYWLS5jytf2M6oUzFMNlrA2ST5ZCA0EfrzzyQim4)
> 
> Pixel intensity of this is based on Murrays altitude dems, but colour now is based on slope direction. I would put money on long lasting patches being in bright purple/blue/red

@SimonFisher92 this plot is a work of art! Agree with all the rest of what you guys have said about slope features.

**Comment by murraycutforth** [comment]
I would speculate that a NN would be better at interpreting the gradient given in Cartesian form (dx, dy) rather than polar form (phi, r) because the discontinuity in phi between 0 and 2pi could be difficult for a NN to learn?

**Comment by murraycutforth** [comment]
@SimonFisher92 @ipoole 

Just an update on the download branch, I worked on a big refactor yesterday to use xarray objects, and have successfully tested this. I think it's a big improvement. We now have a single netCDF file storing an xarray dataset which contains everything (all bands, all classification info, plus elevation/slope) for a single year and a single patch. The best thing about xarray is that each dataset object is completely standalone, because the x/y/time coordinates of each grid point are given, as well as the names of each band. It's super easy to convert a band back to numpy arrays as well. I think xarray and netCDF is pretty industry standard for geospatial stuff. I know that climate modellers all share their results as netCDF files.

Here's an example of loading all the Creag Meagaidh data for 2020:
![image](https://github.com/SimonFisher92/Scottish_Snow/assets/11088372/ef3637a5-c464-423b-9ec4-6a11eed548d4)

Getting the raw numpy array for band two is as easy as: `ds["B02"].values`

Or you can get the RGB bands for the first time point like this:
![image](https://github.com/SimonFisher92/Scottish_Snow/assets/11088372/ff503eed-330d-4bc9-92a6-dba2fff5c907)

**Comment by murraycutforth** [comment]
Here's a little animation of An Riabhachan this year from those visualisations:

![output](https://github.com/SimonFisher92/Scottish_Snow/assets/11088372/72ea1530-db00-4705-a943-0b49c47fd0f9)

It's a subject for a fresh thread but I've noticed lots of false positives in the snow probabilities. I need to double check that the snow probability band is consistent the the snow mask in the SCL band though.

**Comment by SimonFisher92** [comment]
Issue is now merged
